# Generated by Django 3.0.7 on 2020-06-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='stripe_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
